spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=CST
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath*:mapper/*.xml

